# Generated by Django 3.1.8 on 2021-04-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='article',
            new_name='file',
        ),
    ]
